Only put built-in config files in custom ".dte.config" section on Linux
It hasn't been tested on any other platform and seems to cause problems
on at least OpenBSD:

    error: builtin_syntax_c causes a section type conflict

It seems like this may be caused by a GCC bug. Either way, it's not at
all necessary and should be disabled for any platform that isn't
continuously tested.