Set "/bin/bash" as entry-point for "void-linux" job in .gitlab-ci.yml
Otherwise GitLab's idiotic, non-portable checkout scripts run with
"/bin/sh" and cause the job runner to fail during initialization, after
printing the following error message:

    Skipping Git submodules setup
    /usr/bin/sh: 1: set: Illegal option -o pipefail
    /usr/bin/sh: 1: set: Illegal option -o pipefail
    ERROR: Job failed: exit code 2