Use `void*` cast in `iconv_wrapper()`, instead of NetBSD-specific hack
This is to fix the following compilation error on Illumos:

    $ gmake
          CC  build/convert.o
    src/convert.c: In function 'iconv_wrapper':
    src/convert.c:243:22: error: passing argument 2 of 'iconv' from
    incompatible pointer type [-Wincompatible-pointer-types]
      243 |     return iconv(cd, in, inbytesleft, outbuf, outbytesleft);
          |                      ^~
          |                      |
          |                      char **
    In file included from src/convert.c:194:
    /usr/include/iconv.h:47:32: note: expected 'const char ** restrict'
    but argument is of type 'char **'
       47 | extern size_t   iconv(iconv_t, const char **_RESTRICT_KYWD,
          |                                ^
    gmake: *** [mk/build.mk:194: build/convert.o] Error 1

    $ uname -a
    SunOS build 5.11 omnios-r151058-01b2a644afb i86pc i386 i86pc illumos
    $ gcc -v
    Target: x86_64-pc-solaris2.11
    gcc version 15.2.0 (OmniOS 151058/15.2.0-il-0)
    $ clang -v
    OmniOS/151058 clang version 22.1.8
    Target: x86_64-pc-solaris2.11

The above was originally reported by @extrowerk on GitHub and has been
edited slightly for conciseness.