Improve IGNORE_WARNING() macro
This should allow it to be used with warning flags that aren't known
by the compiler without giving another warning for that.

It should also allow using it unconditionally, to avoid yet more
warnings caused by "diagnostic pop" with no matching "push", for
example:

    error: pragma diagnostic pop could not pop, no matching push
    [-Werror,-Wunknown-pragmas]