Fix compilation on CentOS 7 (GCC 4.8.5)
This version of GCC emits pointless warnings about "missing field
initializers", which become errors on CI (via "-Werror"):

> test/command.c:115:5: error: missing initializer for field 'flags' of
> 'CommandArgs' [-Werror=missing-field-initializers]