Add 2 missing semi-colons after `BUG_ON()` statements
The current definitions (with and without `DEBUG > 0`) don't produce
warnings when this is expanded, but making it expand to e.g. a
`__builtin_assume()` statement produces warnings like:

> src/shift.c:26:5: error: '__assume__' attribute cannot be applied
> to a declaration